### ISSUE TITLE
build 时发生错误

### ISSUE THREAD

**Issue by oyiadin** [whtsky/catsup-theme-phase#1]
所有回溯信息：

``` text
Traceback (most recent call last):
  File "/usr/local/bin/catsup", line 9, in <module>
    load_entry_point('catsup==0.3.5', 'console_scripts', 'catsup')()
  File "/usr/local/lib/python2.7/dist-packages/catsup-0.3.5-py2.7.egg/catsup/cli.py", line 232, in main
    parguments.run()
  File "/usr/local/lib/python2.7/dist-packages/parguments-0.3.2-py2.7.egg/parguments/__init__.py", line 176, in run
    result = cmd(**args)
  File "/usr/local/lib/python2.7/dist-packages/parguments-0.3.2-py2.7.egg/parguments/__init__.py", line 19, in __call__
    self._func(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/catsup-0.3.5-py2.7.egg/catsup/cli.py", line 72, in build
    generator.generate()
  File "/usr/local/lib/python2.7/dist-packages/catsup-0.3.5-py2.7.egg/catsup/generator/__init__.py", line 134, in generate
    self.generate_posts()
  File "/usr/local/lib/python2.7/dist-packages/catsup-0.3.5-py2.7.egg/catsup/generator/__init__.py", line 95, in generate_posts
    post.render(self.renderer)
  File "/usr/local/lib/python2.7/dist-packages/catsup-0.3.5-py2.7.egg/catsup/models.py", line 34, in render
    renderer.render_to(template_name, self.permalink, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/catsup-0.3.5-py2.7.egg/catsup/generator/renderer.py", line 52, in render_to
    html = self.render(template, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/catsup-0.3.5-py2.7.egg/catsup/generator/renderer.py", line 46, in render
    return self.env.get_template(template).render(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.7.2-py2.7.egg/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.7.2-py2.7.egg/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/oyiadin/github/build-demo/themes/phase/templates/post.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/home/oyiadin/github/build-demo/themes/phase/templates/layout.html", line 24, in top-level template code
    {% block content %}{% endblock %}
  File "/home/oyiadin/github/build-demo/themes/phase/templates/post.html", line 15, in block "content"
    <time datetime="{{ post.updated | xmldatetime }}">
  File "<string>", line 2, in xmldatetime
jinja2.exceptions.UndefinedError: 'catsup.models.Post object' has no attribute 'updated'
```

catsup 版本：0.3.5。

**Comment by whtsky** [comment]
这个主题基本被遗弃了..
